# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1By_bdIKpL557kKucHrt74eMqOjXPmXk8
"""

list = ["月曜日は晴れです", "火曜日は雨です", "水曜日は晴れです", "木曜日は晴れです", "金曜日は曇りです", "土曜日は曇りのち雨です", "日曜日は雷雨です"]
print(list[2])

dictionary = {"mom": "晴れ", "tue": "雨", "wed": "晴れ", "thu": "晴れ", "fri": "曇り", "sat": "曇りのち雨", "sun": "雷雨"}
print(dictionary["wed"])