# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1yWEfa3rxi1y45rt7BQ5Hj8B1x0P8Fkhj
"""

class Human:
  def __init__(self, name, age):
    self.name = name
    self.age = age

  def set_name(self, name):
    self.name = name
  def set_age(self, age):
    self.age = age

  def printinfo(self):
    print("名前:", self.name)
    print("年齢:", self.age)


human = Human("侍太郎", 40)


human.printinfo()