# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1By_bdIKpL557kKucHrt74eMqOjXPmXk8
"""

import random

var = random.randint(1,100)

if var % 3 == 0:
    print("Fizz")

elif var % 5 == 0:
    print("Buzz")

if var % 3 == 0 and var % 5 == 0:
  print("FizzBuzz")

else:
  print(var)

