# -*- coding: utf-8 -*-
"""Untitled1.ipynb のコピー

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1XGfKx5zK31B2uCYvHvEnbT5g9fVlHsp-
"""

def tax_price(price):
  total = price * 1.1
  print(f"{total}円")

tax_price(100)