# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1By_bdIKpL557kKucHrt74eMqOjXPmXk8
"""

upper_base = 10
low_base = 20
height = 5

trapezoid_area = (upper_base + low_base) * height / 2

print(f"台形の面積は{trapezoid_area}㎠です")