# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1yWEfa3rxi1y45rt7BQ5Hj8B1x0P8Fkhj
"""

price1 = 100
price2 = 200
tax = 1.1

def total():
    return price1 + price2

print (total() * tax)