# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1yWEfa3rxi1y45rt7BQ5Hj8B1x0P8Fkhj
"""

class Human:
  def __init__(self, name, age):
    self.name = name
    self.age = age

  def check_adult(self):
    if self.age >=20:
      print(f"{self.name}は大人です。")
    else:
      print(f"{self.name}は大人ではありません。")

human_list1 = Human("一郎", 10)
human_list2 = Human("二朗", 12)
human_list3 = Human("三郎", 20)
human_list4 = Human("四郎", 22)
human_list5 = Human("五郎", 30)

human_list = [human_list1,human_list2,human_list3,human_list4,human_list5]


for i in range(0, 5):
  human_list[i].check_adult()