# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1By_bdIKpL557kKucHrt74eMqOjXPmXk8
"""

list = ["水","金","地","火","木","土","天","海","冥"]

for test in list:
    print(test)

list = ["水","金","地","火","木","土","天","海","冥"]

count = 0

while count < 2:
  for test in list:
    print(test)
    count += 1